#!/bin/sh

set -e

width=10800
height=3600
outdir="output/${width}x${height}-$(date +%s)"
mkdir -p "$outdir"

function make_gift() {
    color="$1"
    outpath="$outdir/${color:1}.png"
    echo "Generating lines in $outpath..."
    python lines.py --width=$width --height=$height --color=$color > "$outpath"
}

make_gift "#094fb1"
make_gift "#0c601e"

open "$outdir"/*.png
